[package]
name = "mesh"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Chao Zhang <chaz@dtu.dk>"]
license = "MIT"
description = "A package for parsing and rendering 2D and 3D Gmsh .msh files directly in Typst."
categories = ["visualization", "engineering"]
